#!/bin/sh

if [ -d /usr/lib/ccache ]; then
    export PATH="/usr/lib/ccache:$PATH"
fi

debian/rules clean 2>&1
dpkg-source --before-build .
debian/rules build 2>&1

export LANG=C.UTF-8
export LC_ALL=C.UTF-8
[ -e debian/tests.home ] || mkdir debian/tests.home
HOME=debian/tests.home dh_auto_test
ret=$?
rm -rf debian/home/tests.home
exit $ret
