#!/bin/sh

export LANG=C.UTF-8
export LC_ALL=C.UTF-8

if [ -z "$HOME" ] || [ ! -d "$HOME" ]; then
    [ -e debian/tests.home ] || mkdir debian/tests.home
    export HOME="$(pwd)/debian/tests.home"
    trap "rm -rf debian/tests.home" EXIT
fi

dh_auto_test
